# Generated by Django 5.0.3 on 2024-09-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_checkpoint_gpslocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GPSLocation',
        ),
    ]
